version: '2.2'
services:
  config-server:
    build: ConfigServer
    image: gstearmit/config-server:1.0
    restart: always
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - 8888:8888

  email-service:
    build: EmailService
    image: gstearmit/email-service:1.0
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 8082:8082

  user-service:
    build: UserAccount
    image: gstearmit/user-service:1.0
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 8081:8081

  discovery-service:
    build: EurekaServer
    image: gstearmit/discovery-service:1.0
    restart: always
    ports:
      - 8761:8761